### ISSUE TITLE
unitizers update problems

### ISSUE THREAD

**Issue by hubabe** [brodieG/unitizer#273] opened 2020-11-24 14:30 UTC
Again problems updating unitizer version 1.4.12
RStudio
sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/atlas/libblas.so.3.10.3
LAPACK: /usr/lib/x86_64-linux-gnu/atlas/liblapack.so.3.10.3

locale:
 [1] LC_CTYPE=es_CO.UTF-8       LC_NUMERIC=C               LC_TIME=es_CO.UTF-8       
 [4] LC_COLLATE=es_CO.UTF-8     LC_MONETARY=es_CO.UTF-8    LC_MESSAGES=es_CO.UTF-8   
 [7] LC_PAPER=es_CO.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=es_CO.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.3 tools_4.0.3    yaml_2.2.1 

install.packages("unitizer")
Installing package into ‘/home/hugo/R/x86_64-pc-linux-gnu-library/4.0’
(as ‘lib’ is unspecified)
probando la URL 'https://cloud.r-project.org/src/contrib/unitizer_1.4.12.tar.gz'
Content type 'application/x-gzip' length 693207 bytes (676 KB)
==================================================
downloaded 676 KB

* installing *source* package ‘unitizer’ ...
** package ‘unitizer’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** demo
** inst
** byte-compile and prepare package for lazy loading
Error in completeSubclasses(classDef2, class1, obj, where) : 
  tentativa de obtener un slot "subclasses" de un objeto de una clase básica ("NULL") sin slots
Error: package or namespace load failed for ‘dbplyr’:
 .onLoad failed in loadNamespace() for 'dbplyr', details:
  call: setClass(cl, contains = c(prevClass, "VIRTUAL"), where = where)
  error: error in contained classes ("character") for class “ident”; class definition removed from ‘dbplyr’
Error in .requirePackage(package) : 
  unable to find required package ‘dbplyr’
Calls: <Anonymous> ... .recacheSubclasses -> getClassDef -> .requirePackage
Ejecución interrumpida
ERROR: lazy loading failed for package ‘unitizer’
* removing ‘/home/hugo/R/x86_64-pc-linux-gnu-library/4.0/unitizer’
* restoring previous ‘/home/hugo/R/x86_64-pc-linux-gnu-library/4.0/unitizer’
Warning in install.packages :
  installation of package ‘unitizer’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmp57DKRp/downloaded_packages’

Updating unitizer from command line
install.packages("unitizer", dependencies = TRUE)
Installing package into ‘/home/hugo/R/x86_64-pc-linux-gnu-library/4.0’
(as ‘lib’ is unspecified)
probando la URL 'https://cloud.r-project.org/src/contrib/unitizer_1.4.12.tar.gz'
Content type 'application/x-gzip' length 693207 bytes (676 KB)
==================================================
downloaded 676 KB

* installing *source* package ‘unitizer’ ...
** package ‘unitizer’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** demo
** inst
** byte-compile and prepare package for lazy loading
Error in completeSubclasses(classDef2, class1, obj, where) : 
  tentativa de obtener un slot "subclasses" de un objeto de una clase básica ("NULL") sin slots
Error: package or namespace load failed for ‘dbplyr’:
 .onLoad failed in loadNamespace() for 'dbplyr', details:
  call: setClass(cl, contains = c(prevClass, "VIRTUAL"), where = where)
  error: error in contained classes ("character") for class “ident”; class definition removed from ‘dbplyr’
Error in .requirePackage(package) : 
  unable to find required package ‘dbplyr’
Calls: <Anonymous> ... .recacheSubclasses -> getClassDef -> .requirePackage
Ejecución interrumpida
ERROR: lazy loading failed for package ‘unitizer’
* removing ‘/home/hugo/R/x86_64-pc-linux-gnu-library/4.0/unitizer’
* restoring previous ‘/home/hugo/R/x86_64-pc-linux-gnu-library/4.0/unitizer’

The downloaded source packages are in
	‘/tmp/RtmpgGCZkB/downloaded_packages’
Warning message:
In install.packages("unitizer", dependencies = TRUE) :
  installation of package ‘unitizer’ had non-zero exit status

**Comment by brodieG** [comment] 2020-11-24 15:49
I can't reproduce at the moment, but this code leads me to think maybe you don't have an updated version of `dplyr` installed:

```
function (...) 
{
    register_s3_method("dplyr", "union", "tbl_lazy")
    register_s3_method("dplyr", "intersect", "tbl_lazy")
    register_s3_method("dplyr", "setdiff", "tbl_lazy")
    register_s3_method("dplyr", "setdiff", "tbl_Oracle")
    register_s3_method("dplyr", "setdiff", "OraConnection")
    register_s3_method("dplyr", "filter", "tbl_lazy")
    if (utils::packageVersion("dplyr") >= "0.8.99") {
        register_s3_method("dplyr", "group_by_drop_default", 
            "tbl_lazy")
        methods::setOldClass(c("ident_q", "ident", "character"), 
            ident_q())
        methods::setOldClass(c("ident", "character"), ident())
        methods::setOldClass(c("sql", "character"), sql())
    }
}
<bytecode: 0x7fa4ca9af008>
<environment: namespace:dbplyr>
```
Will you run `packageVersion('dplyr')`, and if it's not > 0.8.99 update that package and try re-installing?

**Comment by brodieG** [comment] 2020-11-24 16:22
I saw you forked the package, just fyi I just merged the latest CRAN version to master.

**Comment by brodieG** [comment] 2021-04-20 00:28
I'm closing this as I haven't heard anything in a while.  Feel free to re-open if you're able to isolate this further than we've gotten previously.

**Closed by brodieG** 2021-04-20 00:28 UTC
